[package]
name = "tasks"
version = "0.1.0"
edition = "2021"


[dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
ndarray-rand = "0.14.0"

[dependencies.sdl2]
version = "0.36"
default-features = false
features = ["gfx"]
