task = "CatchingTask"

[evolution]
population_size =  50
parent_fraction =  0.3
elites = 2
fitness_goal = 90.0
max_generations =  50

[genome]
max_neurons =  13
initial_neuron_count_range = [2, 5]
initial_connection_count_range = [3, 4]

n_mutations = 2
mutate_connection_probability = 0.8
mutate_toggle_connection_probability = 0.3
mutate_add_connection_probability = 0.03
mutate_add_neuron_probability = 0.02
