log_level = "debug"

process = "experiment"

model = "base_model"
task = "pattern_similarity"

[experiment]
n_runs = 50
plot_individual_runs = false

[optimizer]
max_generations = 1000

[snes]
pop_size = 100

lr_mu = 0.1
lr_sigma = 0.01

init_sigma = 1.0
init_mu_mean = 0.0
init_mu_stddev = 1.0

[eval]
max_threads = 64
trials = 8

[batch]
batch_size = 32

[rsnn]
n = 128

[rsnn.model]
k = 8
k_in = 1
k_out = 1

distance_threshold = 3.0
max_coordinate = 10.0

exc_w = 1.1 # 0.33
inh_w = 1.32 # 0.41

input_w = 1.44 # 0.55
