log_level = "debug"

process = "default"
model = "uniform_model"

task = "pattern_similarity"

[experiment]
n_runs = 50
save_individual_runs = true
desc = ""

[optimizer]
max_generations = 200

[snes]
pop_size = 100

lr_mu = 0.1
lr_sigma = 0.01

init_sigma = 1.0
init_mu_mean = 0.0
init_mu_stddev = 1.0

[eval]
max_threads = 64
trials = 1

[batch]
batch_size = 32

[generator] # Model-independent parameters
n = 128

[generator.model] # Model-specific parameters
# typed parameters
k = 8
k_in = 1
k_out = 1

# Geometric parameters
distance_threshold = 3.0
max_coordinate = 10.0

# Parameters for static weights
exc_w = 1.1
inh_w = 1.32
input_w = 1.44
