## Default
model = "typed"
task = "polebalance"
algorithm = "nes"

log_level = "debug"

[optimizer]
max_generations = 100
min_gen_before_restart= 25 # minimum 25

[nes]
population_size = 10
alpha = 0.01 # 0.001
sigma = 0.1 # 0.1

[eval]
max_threads = 16
trials = 1

[rsnn]
n = 32

[rsnn.model]
k = 8
max_w = 10.0
