model = "typed"
task = "catching"
algorithm = "nes"

log_level = "debug"

[optimizer]
max_generations = 1000
min_gen_before_restart= 100
max_gen_without_improvement= 20

[nes]
population_size = 100
alpha = 0.001
sigma = 0.1

[eval]
max_threads = 16
trials = 1


[rsnn]
n = 32

[rsnn.model]
