## Default
model = "typed"
task = "catching"
algorithm = "nes"

log_level = "debug"

[optimizer]
max_generations = 1000
min_gen_before_restart= 50 # minimum 25

[nes]
population_size = 50
alpha = 0.001 # 0.001
sigma = 0.1 # 0.1

init_mean =    0.0
init_stddev =  1.0

[eval]
max_threads = 16
trials = 1

[rsnn]
n = 64

[rsnn.model]
k = 8
max_w = 1.0
