# Default
process = "experiment"

model = "typed"
task = "pattern"
algorithm = "snes"

log_level = "debug"

[experiment]
n_runs = 50

[optimizer]
max_generations = 200

[snes]
pop_size = 100
lr_mu = 0.1
lr_sigma = 0.01

[eval]
max_threads = 32
trials = 1

[batch]
batch_size = 32

[rsnn]
n = 64

[rsnn.model]
k = 8
max_w = 1.0
