log_level = "debug"

process = "default"

model = "base_model"
task = "pattern"
algorithm = "snes"


[experiment]
n_runs = 50
plot_individual_runs = false

[optimizer]
max_generations = 250

[snes]
pop_size = 100

lr_mu = 0.1
lr_sigma = 0.01

init_sigma = 1.0
init_mu_mean = 0.0
init_mu_stddev = 1.0

[eval]
max_threads = 64
trials = 8

[batch]
batch_size = 32

[rsnn]
n = 128

[rsnn.model]
k = 6
k_out = 3
k_in = 4

distance_threshold = 3.0
max_coordinate = 10.0
