## Default
process = "default"

model = "typed"
task = "mnist" # "mnist" "pattern"
algorithm = "snes"

log_level = "debug"


[batch]
batch_size = 64

[optimizer]
max_generations = 200000
min_gen_before_restart= 200 # minimum 25

[snes]
pop_size = 100
lr_mu = 0.1
lr_sigma = 0.01

[eval]
max_threads = 32
trials = 2

[rsnn]
n = 128

[rsnn.model]
k = 10
max_w = 1.0
