task = "catching"
genome = "matrix"

[evolution]
population_size =  50
parent_fraction =  0.3
elites = 2
fitness_goal = 999999.0
max_generations =  50

[matrix_genome]
max_neurons =  25
initial_neuron_count_range = [3, 15]
initial_connection_count_range = [4, 20]

n_mutations = 2
mutate_connection_probability = 0.8
mutate_toggle_connection_probability = 0.3
mutate_add_connection_probability = 0.03
mutate_add_neuron_probability = 0.02

inhibitory_probability = 0.0
