# Default
process = "default"
#process = "test"

model = "test_model"
#model = "minimal"
#model = "gt_model"

#task = "testing"
#task = "pattern"
task = "multipattern"

algorithm = "snes"

log_level = "debug"

[experiment]
n_runs = 10

[optimizer]
max_generations = 500

[snes]
pop_size = 100
lr_mu = 0.1
lr_sigma = 0.01 # 0.01

init_sigma = 2.0        # 1.0
init_mu_mean = 0.0     # 0.0
init_mu_stddev = 2.0    # 2.0

[eval]
max_threads = 32
trials = 10

[batch]
batch_size = 16

[rsnn]
n = 128

[rsnn.model]
k = 6
in_k = 1
out_k = 1

max_w = 1.0

distance_threshold = 3.0
max_coordinate = 10.0
