task = "xor"
genome = "matrix"

log_level ="info"

[evolution]
max_generations = 200
population_size = 100

fitness_goal = 100.0

[matrix_genome]
max_neurons =  75
initial_neuron_count_range = [5, 10]
initial_connection_count_range = [2, 3]

n_mutations = 2
mutate_connection_probability = 0.83
mutate_toggle_connection_probability = 0.10
mutate_add_connection_probability = 0.05
mutate_add_neuron_probability = 0.02

inhibitory_probability = 0.3
